In [3]:
import pandas as pd
import glob
import os

street_files = glob.glob("./**/*-street.csv", recursive=True)

In [10]:
street_files

['.\\2023-02\\2023-02-avon-and-somerset-street.csv',
 '.\\2023-02\\2023-02-cambridgeshire-street.csv',
 '.\\2023-02\\2023-02-cheshire-street.csv',
 '.\\2023-02\\2023-02-cumbria-street.csv',
 '.\\2023-02\\2023-02-derbyshire-street.csv',
 '.\\2023-02\\2023-02-durham-street.csv',
 '.\\2023-02\\2023-02-gloucestershire-street.csv',
 '.\\2023-02\\2023-02-hampshire-street.csv',
 '.\\2023-02\\2023-02-hertfordshire-street.csv',
 '.\\2023-02\\2023-02-lancashire-street.csv',
 '.\\2023-02\\2023-02-norfolk-street.csv',
 '.\\2023-02\\2023-02-suffolk-street.csv',
 '.\\2023-03\\2023-03-avon-and-somerset-street.csv',
 '.\\2023-03\\2023-03-cambridgeshire-street.csv',
 '.\\2023-03\\2023-03-cheshire-street.csv',
 '.\\2023-03\\2023-03-cumbria-street.csv',
 '.\\2023-03\\2023-03-derbyshire-street.csv',
 '.\\2023-03\\2023-03-durham-street.csv',
 '.\\2023-03\\2023-03-gloucestershire-street.csv',
 '.\\2023-03\\2023-03-hampshire-street.csv',
 '.\\2023-03\\2023-03-hertfordshire-street.csv',
 '.\\2023-03\\2023-03-lancashire-street.csv',
 '.\\2023-03\\2023-03-norfolk-street.csv',
 '.\\2023-03\\2023-03-suffolk-street.csv',
 '.\\2023-04\\2023-04-avon-and-somerset-street.csv',
 '.\\2023-04\\2023-04-cambridgeshire-street.csv',
 '.\\2023-04\\2023-04-cheshire-street.csv',
 '.\\2023-04\\2023-04-cumbria-street.csv',
 '.\\2023-04\\2023-04-derbyshire-street.csv',
 '.\\2023-04\\2023-04-durham-street.csv',
 '.\\2023-04\\2023-04-gloucestershire-street.csv',
 '.\\2023-04\\2023-04-hampshire-street.csv',
 '.\\2023-04\\2023-04-hertfordshire-street.csv',
 '.\\2023-04\\2023-04-lancashire-street.csv',
 '.\\2023-04\\2023-04-norfolk-street.csv',
 '.\\2023-04\\2023-04-suffolk-street.csv',
 '.\\2023-05\\2023-05-avon-and-somerset-street.csv',
 '.\\2023-05\\2023-05-cambridgeshire-street.csv',
 '.\\2023-05\\2023-05-cheshire-street.csv',
 '.\\2023-05\\2023-05-cumbria-street.csv',
 '.\\2023-05\\2023-05-derbyshire-street.csv',
 '.\\2023-05\\2023-05-durham-street.csv',
 '.\\2023-05\\2023-05-gloucestershire-street.csv',
 '.\\2023-05\\2023-05-hampshire-street.csv',
 '.\\2023-05\\2023-05-hertfordshire-street.csv',
 '.\\2023-05\\2023-05-lancashire-street.csv',
 '.\\2023-05\\2023-05-norfolk-street.csv',
 '.\\2023-05\\2023-05-suffolk-street.csv',
 '.\\2023-06\\2023-06-avon-and-somerset-street.csv',
 '.\\2023-06\\2023-06-cambridgeshire-street.csv',
 '.\\2023-06\\2023-06-cheshire-street.csv',
 '.\\2023-06\\2023-06-cumbria-street.csv',
 '.\\2023-06\\2023-06-derbyshire-street.csv',
 '.\\2023-06\\2023-06-durham-street.csv',
 '.\\2023-06\\2023-06-gloucestershire-street.csv',
 '.\\2023-06\\2023-06-hampshire-street.csv',
 '.\\2023-06\\2023-06-hertfordshire-street.csv',
 '.\\2023-06\\2023-06-lancashire-street.csv',
 '.\\2023-06\\2023-06-norfolk-street.csv',
 '.\\2023-06\\2023-06-suffolk-street.csv',
 '.\\2023-07\\2023-07-avon-and-somerset-street.csv',
 '.\\2023-07\\2023-07-cambridgeshire-street.csv',
 '.\\2023-07\\2023-07-cheshire-street.csv',
 '.\\2023-07\\2023-07-cumbria-street.csv',
 '.\\2023-07\\2023-07-derbyshire-street.csv',
 '.\\2023-07\\2023-07-durham-street.csv',
 '.\\2023-07\\2023-07-gloucestershire-street.csv',
 '.\\2023-07\\2023-07-hampshire-street.csv',
 '.\\2023-07\\2023-07-hertfordshire-street.csv',
 '.\\2023-07\\2023-07-lancashire-street.csv',
 '.\\2023-07\\2023-07-norfolk-street.csv',
 '.\\2023-07\\2023-07-suffolk-street.csv',
 '.\\2023-08\\2023-08-avon-and-somerset-street.csv',
 '.\\2023-08\\2023-08-cambridgeshire-street.csv',
 '.\\2023-08\\2023-08-cheshire-street.csv',
 '.\\2023-08\\2023-08-cumbria-street.csv',
 '.\\2023-08\\2023-08-derbyshire-street.csv',
 '.\\2023-08\\2023-08-durham-street.csv',
 '.\\2023-08\\2023-08-gloucestershire-street.csv',
 '.\\2023-08\\2023-08-hampshire-street.csv',
 '.\\2023-08\\2023-08-hertfordshire-street.csv',
 '.\\2023-08\\2023-08-lancashire-street.csv',
 '.\\2023-08\\2023-08-norfolk-street.csv',
 '.\\2023-08\\2023-08-suffolk-street.csv',
 '.\\2023-09\\2023-09-avon-and-somerset-street.csv',
 '.\\2023-09\\2023-09-cambridgeshire-street.csv',
 '.\\2023-09\\2023-09-cheshire-street.csv',
 '.\\2023-09\\2023-09-cumbria-street.csv',
 '.\\2023-09\\2023-09-derbyshire-street.csv',
 '.\\2023-09\\2023-09-durham-street.csv',
 '.\\2023-09\\2023-09-gloucestershire-street.csv',
 '.\\2023-09\\2023-09-hampshire-street.csv',
 '.\\2023-09\\2023-09-hertfordshire-street.csv',
 '.\\2023-09\\2023-09-lancashire-street.csv',
 '.\\2023-09\\2023-09-norfolk-street.csv',
 '.\\2023-09\\2023-09-suffolk-street.csv',
 '.\\2023-10\\2023-10-avon-and-somerset-street.csv',
 '.\\2023-10\\2023-10-cambridgeshire-street.csv',
 '.\\2023-10\\2023-10-cheshire-street.csv',
 '.\\2023-10\\2023-10-cumbria-street.csv',
 '.\\2023-10\\2023-10-derbyshire-street.csv',
 '.\\2023-10\\2023-10-durham-street.csv',
 '.\\2023-10\\2023-10-gloucestershire-street.csv',
 '.\\2023-10\\2023-10-hampshire-street.csv',
 '.\\2023-10\\2023-10-hertfordshire-street.csv',
 '.\\2023-10\\2023-10-lancashire-street.csv',
 '.\\2023-10\\2023-10-norfolk-street.csv',
 '.\\2023-10\\2023-10-suffolk-street.csv',
 '.\\2023-11\\2023-11-avon-and-somerset-street.csv',
 '.\\2023-11\\2023-11-cambridgeshire-street.csv',
 '.\\2023-11\\2023-11-cheshire-street.csv',
 '.\\2023-11\\2023-11-cumbria-street.csv',
 '.\\2023-11\\2023-11-derbyshire-street.csv',
 '.\\2023-11\\2023-11-durham-street.csv',
 '.\\2023-11\\2023-11-gloucestershire-street.csv',
 '.\\2023-11\\2023-11-hampshire-street.csv',
 '.\\2023-11\\2023-11-hertfordshire-street.csv',
 '.\\2023-11\\2023-11-lancashire-street.csv',
 '.\\2023-11\\2023-11-norfolk-street.csv',
 '.\\2023-11\\2023-11-suffolk-street.csv',
 '.\\2023-12\\2023-12-avon-and-somerset-street.csv',
 '.\\2023-12\\2023-12-cambridgeshire-street.csv',
 '.\\2023-12\\2023-12-cheshire-street.csv',
 '.\\2023-12\\2023-12-cumbria-street.csv',
 '.\\2023-12\\2023-12-derbyshire-street.csv',
 '.\\2023-12\\2023-12-durham-street.csv',
 '.\\2023-12\\2023-12-gloucestershire-street.csv',
 '.\\2023-12\\2023-12-hampshire-street.csv',
 '.\\2023-12\\2023-12-hertfordshire-street.csv',
 '.\\2023-12\\2023-12-lancashire-street.csv',
 '.\\2023-12\\2023-12-norfolk-street.csv',
 '.\\2023-12\\2023-12-suffolk-street.csv',
 '.\\2024-01\\2024-01-avon-and-somerset-street.csv',
 '.\\2024-01\\2024-01-cambridgeshire-street.csv',
 '.\\2024-01\\2024-01-cheshire-street.csv',
 '.\\2024-01\\2024-01-cumbria-street.csv',
 '.\\2024-01\\2024-01-derbyshire-street.csv',
 '.\\2024-01\\2024-01-durham-street.csv',
 '.\\2024-01\\2024-01-gloucestershire-street.csv',
 '.\\2024-01\\2024-01-hampshire-street.csv',
 '.\\2024-01\\2024-01-hertfordshire-street.csv',
 '.\\2024-01\\2024-01-lancashire-street.csv',
 '.\\2024-01\\2024-01-norfolk-street.csv',
 '.\\2024-01\\2024-01-suffolk-street.csv',
 '.\\2024-02\\2024-02-avon-and-somerset-street.csv',
 '.\\2024-02\\2024-02-cambridgeshire-street.csv',
 '.\\2024-02\\2024-02-cheshire-street.csv',
 '.\\2024-02\\2024-02-cumbria-street.csv',
 '.\\2024-02\\2024-02-derbyshire-street.csv',
 '.\\2024-02\\2024-02-durham-street.csv',
 '.\\2024-02\\2024-02-gloucestershire-street.csv',
 '.\\2024-02\\2024-02-hampshire-street.csv',
 '.\\2024-02\\2024-02-hertfordshire-street.csv',
 '.\\2024-02\\2024-02-lancashire-street.csv',
 '.\\2024-02\\2024-02-norfolk-street.csv',
 '.\\2024-02\\2024-02-suffolk-street.csv',
 '.\\2024-03\\2024-03-avon-and-somerset-street.csv',
 '.\\2024-03\\2024-03-cambridgeshire-street.csv',
 '.\\2024-03\\2024-03-cheshire-street.csv',
 '.\\2024-03\\2024-03-cumbria-street.csv',
 '.\\2024-03\\2024-03-derbyshire-street.csv',
 '.\\2024-03\\2024-03-durham-street.csv',
 '.\\2024-03\\2024-03-gloucestershire-street.csv',
 '.\\2024-03\\2024-03-hampshire-street.csv',
 '.\\2024-03\\2024-03-hertfordshire-street.csv',
 '.\\2024-03\\2024-03-lancashire-street.csv',
 '.\\2024-03\\2024-03-norfolk-street.csv',
 '.\\2024-03\\2024-03-suffolk-street.csv',
 '.\\2024-04\\2024-04-avon-and-somerset-street.csv',
 '.\\2024-04\\2024-04-cambridgeshire-street.csv',
 '.\\2024-04\\2024-04-cheshire-street.csv',
 '.\\2024-04\\2024-04-cumbria-street.csv',
 '.\\2024-04\\2024-04-derbyshire-street.csv',
 '.\\2024-04\\2024-04-durham-street.csv',
 '.\\2024-04\\2024-04-gloucestershire-street.csv',
 '.\\2024-04\\2024-04-hampshire-street.csv',
 '.\\2024-04\\2024-04-hertfordshire-street.csv',
 '.\\2024-04\\2024-04-lancashire-street.csv',
 '.\\2024-04\\2024-04-norfolk-street.csv',
 '.\\2024-04\\2024-04-suffolk-street.csv',
 '.\\2024-05\\2024-05-avon-and-somerset-street.csv',
 '.\\2024-05\\2024-05-cambridgeshire-street.csv',
 '.\\2024-05\\2024-05-cheshire-street.csv',
 '.\\2024-05\\2024-05-cumbria-street.csv',
 '.\\2024-05\\2024-05-derbyshire-street.csv',
 '.\\2024-05\\2024-05-durham-street.csv',
 '.\\2024-05\\2024-05-gloucestershire-street.csv',
 '.\\2024-05\\2024-05-hampshire-street.csv',
 '.\\2024-05\\2024-05-hertfordshire-street.csv',
 '.\\2024-05\\2024-05-lancashire-street.csv',
 '.\\2024-05\\2024-05-norfolk-street.csv',
 '.\\2024-05\\2024-05-suffolk-street.csv',
 '.\\2024-06\\2024-06-avon-and-somerset-street.csv',
 '.\\2024-06\\2024-06-cambridgeshire-street.csv',
 '.\\2024-06\\2024-06-cheshire-street.csv',
 '.\\2024-06\\2024-06-cumbria-street.csv',
 '.\\2024-06\\2024-06-derbyshire-street.csv',
 '.\\2024-06\\2024-06-durham-street.csv',
 '.\\2024-06\\2024-06-gloucestershire-street.csv',
 '.\\2024-06\\2024-06-hampshire-street.csv',
 '.\\2024-06\\2024-06-hertfordshire-street.csv',
 '.\\2024-06\\2024-06-lancashire-street.csv',
 '.\\2024-06\\2024-06-norfolk-street.csv',
 '.\\2024-06\\2024-06-suffolk-street.csv',
 '.\\2024-07\\2024-07-avon-and-somerset-street.csv',
 '.\\2024-07\\2024-07-cambridgeshire-street.csv',
 '.\\2024-07\\2024-07-cheshire-street.csv',
 '.\\2024-07\\2024-07-cumbria-street.csv',
 '.\\2024-07\\2024-07-derbyshire-street.csv',
 '.\\2024-07\\2024-07-durham-street.csv',
 '.\\2024-07\\2024-07-gloucestershire-street.csv',
 '.\\2024-07\\2024-07-hampshire-street.csv',
 '.\\2024-07\\2024-07-hertfordshire-street.csv',
 '.\\2024-07\\2024-07-lancashire-street.csv',
 '.\\2024-07\\2024-07-norfolk-street.csv',
 '.\\2024-07\\2024-07-suffolk-street.csv',
 '.\\2024-08\\2024-08-avon-and-somerset-street.csv',
 '.\\2024-08\\2024-08-cambridgeshire-street.csv',
 '.\\2024-08\\2024-08-cheshire-street.csv',
 '.\\2024-08\\2024-08-cumbria-street.csv',
 '.\\2024-08\\2024-08-derbyshire-street.csv',
 '.\\2024-08\\2024-08-durham-street.csv',
 '.\\2024-08\\2024-08-gloucestershire-street.csv',
 '.\\2024-08\\2024-08-hampshire-street.csv',
 '.\\2024-08\\2024-08-hertfordshire-street.csv',
 '.\\2024-08\\2024-08-lancashire-street.csv',
 '.\\2024-08\\2024-08-norfolk-street.csv',
 '.\\2024-08\\2024-08-suffolk-street.csv',
 '.\\2024-09\\2024-09-avon-and-somerset-street.csv',
 '.\\2024-09\\2024-09-cambridgeshire-street.csv',
 '.\\2024-09\\2024-09-cheshire-street.csv',
 '.\\2024-09\\2024-09-cumbria-street.csv',
 '.\\2024-09\\2024-09-derbyshire-street.csv',
 '.\\2024-09\\2024-09-durham-street.csv',
 '.\\2024-09\\2024-09-gloucestershire-street.csv',
 '.\\2024-09\\2024-09-hampshire-street.csv',
 '.\\2024-09\\2024-09-hertfordshire-street.csv',
 '.\\2024-09\\2024-09-lancashire-street.csv',
 '.\\2024-09\\2024-09-norfolk-street.csv',
 '.\\2024-09\\2024-09-suffolk-street.csv',
 '.\\2024-10\\2024-10-avon-and-somerset-street.csv',
 '.\\2024-10\\2024-10-cambridgeshire-street.csv',
 '.\\2024-10\\2024-10-cheshire-street.csv',
 '.\\2024-10\\2024-10-cumbria-street.csv',
 '.\\2024-10\\2024-10-derbyshire-street.csv',
 '.\\2024-10\\2024-10-durham-street.csv',
 '.\\2024-10\\2024-10-gloucestershire-street.csv',
 '.\\2024-10\\2024-10-hampshire-street.csv',
 '.\\2024-10\\2024-10-hertfordshire-street.csv',
 '.\\2024-10\\2024-10-lancashire-street.csv',
 '.\\2024-10\\2024-10-norfolk-street.csv',
 '.\\2024-10\\2024-10-suffolk-street.csv',
 '.\\2024-11\\2024-11-avon-and-somerset-street.csv',
 '.\\2024-11\\2024-11-cambridgeshire-street.csv',
 '.\\2024-11\\2024-11-cheshire-street.csv',
 '.\\2024-11\\2024-11-cumbria-street.csv',
 '.\\2024-11\\2024-11-derbyshire-street.csv',
 '.\\2024-11\\2024-11-durham-street.csv',
 '.\\2024-11\\2024-11-gloucestershire-street.csv',
 '.\\2024-11\\2024-11-hampshire-street.csv',
 '.\\2024-11\\2024-11-hertfordshire-street.csv',
 '.\\2024-11\\2024-11-lancashire-street.csv',
 '.\\2024-11\\2024-11-norfolk-street.csv',
 '.\\2024-11\\2024-11-suffolk-street.csv',
 '.\\2024-12\\2024-12-avon-and-somerset-street.csv',
 '.\\2024-12\\2024-12-cambridgeshire-street.csv',
 '.\\2024-12\\2024-12-cheshire-street.csv',
 '.\\2024-12\\2024-12-cumbria-street.csv',
 '.\\2024-12\\2024-12-derbyshire-street.csv',
 '.\\2024-12\\2024-12-durham-street.csv',
 '.\\2024-12\\2024-12-gloucestershire-street.csv',
 '.\\2024-12\\2024-12-hampshire-street.csv',
 '.\\2024-12\\2024-12-hertfordshire-street.csv',
 '.\\2024-12\\2024-12-lancashire-street.csv',
 '.\\2024-12\\2024-12-norfolk-street.csv',
 '.\\2024-12\\2024-12-suffolk-street.csv',
 '.\\2025-01\\2025-01-avon-and-somerset-street.csv',
 '.\\2025-01\\2025-01-cambridgeshire-street.csv',
 '.\\2025-01\\2025-01-cheshire-street.csv',
 '.\\2025-01\\2025-01-cumbria-street.csv',
 '.\\2025-01\\2025-01-derbyshire-street.csv',
 '.\\2025-01\\2025-01-durham-street.csv',
 '.\\2025-01\\2025-01-gloucestershire-street.csv',
 '.\\2025-01\\2025-01-hampshire-street.csv',
 '.\\2025-01\\2025-01-hertfordshire-street.csv',
 '.\\2025-01\\2025-01-lancashire-street.csv',
 '.\\2025-01\\2025-01-norfolk-street.csv',
 '.\\2025-01\\2025-01-suffolk-street.csv',
 '.\\2025-02\\2025-02-avon-and-somerset-street.csv',
 '.\\2025-02\\2025-02-cambridgeshire-street.csv',
 '.\\2025-02\\2025-02-cheshire-street.csv',
 '.\\2025-02\\2025-02-cumbria-street.csv',
 '.\\2025-02\\2025-02-derbyshire-street.csv',
 '.\\2025-02\\2025-02-durham-street.csv',
 '.\\2025-02\\2025-02-gloucestershire-street.csv',
 '.\\2025-02\\2025-02-hampshire-street.csv',
 '.\\2025-02\\2025-02-hertfordshire-street.csv',
 '.\\2025-02\\2025-02-lancashire-street.csv',
 '.\\2025-02\\2025-02-norfolk-street.csv',
 '.\\2025-02\\2025-02-suffolk-street.csv',
 '.\\2025-03\\2025-03-avon-and-somerset-street.csv',
 '.\\2025-03\\2025-03-cambridgeshire-street.csv',
 '.\\2025-03\\2025-03-cheshire-street.csv',
 '.\\2025-03\\2025-03-cumbria-street.csv',
 '.\\2025-03\\2025-03-derbyshire-street.csv',
 '.\\2025-03\\2025-03-durham-street.csv',
 '.\\2025-03\\2025-03-gloucestershire-street.csv',
 '.\\2025-03\\2025-03-hampshire-street.csv',
 '.\\2025-03\\2025-03-hertfordshire-street.csv',
 '.\\2025-03\\2025-03-lancashire-street.csv',
 '.\\2025-03\\2025-03-norfolk-street.csv',
 '.\\2025-03\\2025-03-suffolk-street.csv',
 '.\\2025-04\\2025-04-avon-and-somerset-street.csv',
 '.\\2025-04\\2025-04-cambridgeshire-street.csv',
 '.\\2025-04\\2025-04-cheshire-street.csv',
 '.\\2025-04\\2025-04-cumbria-street.csv',
 '.\\2025-04\\2025-04-derbyshire-street.csv',
 '.\\2025-04\\2025-04-durham-street.csv',
 '.\\2025-04\\2025-04-gloucestershire-street.csv',
 '.\\2025-04\\2025-04-hampshire-street.csv',
 '.\\2025-04\\2025-04-hertfordshire-street.csv',
 '.\\2025-04\\2025-04-lancashire-street.csv',
 '.\\2025-04\\2025-04-norfolk-street.csv',
 '.\\2025-04\\2025-04-suffolk-street.csv',
 '.\\2025-05\\2025-05-avon-and-somerset-street.csv',
 '.\\2025-05\\2025-05-cambridgeshire-street.csv',
 '.\\2025-05\\2025-05-cheshire-street.csv',
 '.\\2025-05\\2025-05-cumbria-street.csv',
 '.\\2025-05\\2025-05-derbyshire-street.csv',
 '.\\2025-05\\2025-05-durham-street.csv',
 '.\\2025-05\\2025-05-gloucestershire-street.csv',
 '.\\2025-05\\2025-05-hampshire-street.csv',
 '.\\2025-05\\2025-05-hertfordshire-street.csv',
 '.\\2025-05\\2025-05-lancashire-street.csv',
 '.\\2025-05\\2025-05-norfolk-street.csv',
 '.\\2025-05\\2025-05-suffolk-street.csv',
 '.\\2025-06\\2025-06-avon-and-somerset-street.csv',
 '.\\2025-06\\2025-06-cambridgeshire-street.csv',
 '.\\2025-06\\2025-06-cheshire-street.csv',
 '.\\2025-06\\2025-06-cumbria-street.csv',
 '.\\2025-06\\2025-06-derbyshire-street.csv',
 '.\\2025-06\\2025-06-durham-street.csv',
 '.\\2025-06\\2025-06-gloucestershire-street.csv',
 '.\\2025-06\\2025-06-hampshire-street.csv',
 '.\\2025-06\\2025-06-hertfordshire-street.csv',
 '.\\2025-06\\2025-06-lancashire-street.csv',
 '.\\2025-06\\2025-06-norfolk-street.csv',
 '.\\2025-06\\2025-06-suffolk-street.csv',
 '.\\2025-07\\2025-07-avon-and-somerset-street.csv',
 '.\\2025-07\\2025-07-cambridgeshire-street.csv',
 '.\\2025-07\\2025-07-cheshire-street.csv',
 '.\\2025-07\\2025-07-cumbria-street.csv',
 '.\\2025-07\\2025-07-derbyshire-street.csv',
 '.\\2025-07\\2025-07-durham-street.csv',
 '.\\2025-07\\2025-07-gloucestershire-street.csv',
 '.\\2025-07\\2025-07-hampshire-street.csv',
 '.\\2025-07\\2025-07-hertfordshire-street.csv',
 '.\\2025-07\\2025-07-lancashire-street.csv',
 '.\\2025-07\\2025-07-norfolk-street.csv',
 '.\\2025-07\\2025-07-suffolk-street.csv',
 '.\\2025-08\\2025-08-avon-and-somerset-street.csv',
 '.\\2025-08\\2025-08-cambridgeshire-street.csv',
 '.\\2025-08\\2025-08-cheshire-street.csv',
 '.\\2025-08\\2025-08-cumbria-street.csv',
 '.\\2025-08\\2025-08-derbyshire-street.csv',
 '.\\2025-08\\2025-08-durham-street.csv',
 '.\\2025-08\\2025-08-gloucestershire-street.csv',
 '.\\2025-08\\2025-08-hampshire-street.csv',
 '.\\2025-08\\2025-08-hertfordshire-street.csv',
 '.\\2025-08\\2025-08-lancashire-street.csv',
 '.\\2025-08\\2025-08-norfolk-street.csv',
 '.\\2025-08\\2025-08-suffolk-street.csv',
 '.\\2025-09\\2025-09-avon-and-somerset-street.csv',
 '.\\2025-09\\2025-09-cambridgeshire-street.csv',
 '.\\2025-09\\2025-09-cheshire-street.csv',
 '.\\2025-09\\2025-09-cumbria-street.csv',
 '.\\2025-09\\2025-09-derbyshire-street.csv',
 '.\\2025-09\\2025-09-durham-street.csv',
 '.\\2025-09\\2025-09-gloucestershire-street.csv',
 '.\\2025-09\\2025-09-hampshire-street.csv',
 '.\\2025-09\\2025-09-hertfordshire-street.csv',
 '.\\2025-09\\2025-09-lancashire-street.csv',
 '.\\2025-09\\2025-09-norfolk-street.csv',
 '.\\2025-09\\2025-09-suffolk-street.csv',
 '.\\2025-10\\2025-10-avon-and-somerset-street.csv',
 '.\\2025-10\\2025-10-cambridgeshire-street.csv',
 '.\\2025-10\\2025-10-cheshire-street.csv',
 '.\\2025-10\\2025-10-cumbria-street.csv',
 '.\\2025-10\\2025-10-derbyshire-street.csv',
 '.\\2025-10\\2025-10-durham-street.csv',
 '.\\2025-10\\2025-10-gloucestershire-street.csv',
 '.\\2025-10\\2025-10-hampshire-street.csv',
 '.\\2025-10\\2025-10-hertfordshire-street.csv',
 '.\\2025-10\\2025-10-lancashire-street.csv',
 '.\\2025-10\\2025-10-norfolk-street.csv',
 '.\\2025-10\\2025-10-suffolk-street.csv',
 '.\\2025-11\\2025-11-avon-and-somerset-street.csv',
 '.\\2025-11\\2025-11-cambridgeshire-street.csv',
 '.\\2025-11\\2025-11-cheshire-street.csv',
 '.\\2025-11\\2025-11-cumbria-street.csv',
 '.\\2025-11\\2025-11-derbyshire-street.csv',
 '.\\2025-11\\2025-11-durham-street.csv',
 '.\\2025-11\\2025-11-gloucestershire-street.csv',
 '.\\2025-11\\2025-11-hampshire-street.csv',
 '.\\2025-11\\2025-11-hertfordshire-street.csv',
 '.\\2025-11\\2025-11-lancashire-street.csv',
 '.\\2025-11\\2025-11-norfolk-street.csv',
 '.\\2025-11\\2025-11-suffolk-street.csv',
 '.\\2025-12\\2025-12-avon-and-somerset-street.csv',
 '.\\2025-12\\2025-12-cambridgeshire-street.csv',
 '.\\2025-12\\2025-12-cheshire-street.csv',
 '.\\2025-12\\2025-12-cumbria-street.csv',
 '.\\2025-12\\2025-12-derbyshire-street.csv',
 '.\\2025-12\\2025-12-durham-street.csv',
 '.\\2025-12\\2025-12-gloucestershire-street.csv',
 '.\\2025-12\\2025-12-hampshire-street.csv',
 '.\\2025-12\\2025-12-hertfordshire-street.csv',
 '.\\2025-12\\2025-12-lancashire-street.csv',
 '.\\2025-12\\2025-12-norfolk-street.csv',
 '.\\2025-12\\2025-12-suffolk-street.csv',
 '.\\2026-01\\2026-01-avon-and-somerset-street.csv',
 '.\\2026-01\\2026-01-cambridgeshire-street.csv',
 '.\\2026-01\\2026-01-cheshire-street.csv',
 '.\\2026-01\\2026-01-cumbria-street.csv',
 '.\\2026-01\\2026-01-derbyshire-street.csv',
 '.\\2026-01\\2026-01-durham-street.csv',
 '.\\2026-01\\2026-01-gloucestershire-street.csv',
 '.\\2026-01\\2026-01-hampshire-street.csv',
 '.\\2026-01\\2026-01-hertfordshire-street.csv',
 '.\\2026-01\\2026-01-lancashire-street.csv',
 '.\\2026-01\\2026-01-norfolk-street.csv',
 '.\\2026-01\\2026-01-suffolk-street.csv']

In [8]:
import os
os.getcwd()

'C:\\Users\\roisi\\Downloads\\crimedataproper'

In [7]:
street_df = pd.concat((pd.read_csv(f) for f in street_files), ignore_index=True)

In [8]:
street_df.info()
street_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3651324 entries, 0 to 3651323
Data columns (total 12 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               object
 1   Month                  object
 2   Reported by            object
 3   Falls within           object
 4   Longitude              float64
 5   Latitude               float64
 6   Location               object
 7   LSOA code              object
 8   LSOA name              object
 9   Crime type             object
 10  Last outcome category  object
 11  Context                float64
dtypes: float64(3), object(9)
memory usage: 334.3+ MB

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,44949804e10105361f806c22620b183ed7b4337bc53c62...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-1.563651,53.550385,On or near Hawthorn Grove,E01007420,Barnsley 016C,Vehicle crime,Status update unavailable,NaN
1,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.491146,51.425008,On or near Maximus Gardens,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN
2,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.509285,51.409716,On or near Barnard Walk,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN
3,df0232499c2a00f19201d41c436bd12608f036f6306a43...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.492876,51.422716,On or near Trajectus Way,E01014399,Bath and North East Somerset 001A,Other theft,Status update unavailable,NaN
4,4ccbf045d0c67899cf4cf81ebf83f1d352701604f1a024...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.491146,51.425008,On or near Maximus Gardens,E01014399,Bath and North East Somerset 001A,Public order,Unable to prosecute suspect,NaN

In [4]:
outcome_files = glob.glob("./**/*-outcomes.csv", recursive=True)

In [14]:
outcome_files

['.\\2023-02\\2023-02-avon-and-somerset-outcomes.csv',
 '.\\2023-02\\2023-02-cambridgeshire-outcomes.csv',
 '.\\2023-02\\2023-02-cheshire-outcomes.csv',
 '.\\2023-02\\2023-02-cumbria-outcomes.csv',
 '.\\2023-02\\2023-02-derbyshire-outcomes.csv',
 '.\\2023-02\\2023-02-durham-outcomes.csv',
 '.\\2023-02\\2023-02-gloucestershire-outcomes.csv',
 '.\\2023-02\\2023-02-hampshire-outcomes.csv',
 '.\\2023-02\\2023-02-hertfordshire-outcomes.csv',
 '.\\2023-02\\2023-02-lancashire-outcomes.csv',
 '.\\2023-02\\2023-02-norfolk-outcomes.csv',
 '.\\2023-02\\2023-02-suffolk-outcomes.csv',
 '.\\2023-03\\2023-03-avon-and-somerset-outcomes.csv',
 '.\\2023-03\\2023-03-cambridgeshire-outcomes.csv',
 '.\\2023-03\\2023-03-cheshire-outcomes.csv',
 '.\\2023-03\\2023-03-cumbria-outcomes.csv',
 '.\\2023-03\\2023-03-derbyshire-outcomes.csv',
 '.\\2023-03\\2023-03-durham-outcomes.csv',
 '.\\2023-03\\2023-03-gloucestershire-outcomes.csv',
 '.\\2023-03\\2023-03-hampshire-outcomes.csv',
 '.\\2023-03\\2023-03-hertfordshire-outcomes.csv',
 '.\\2023-03\\2023-03-lancashire-outcomes.csv',
 '.\\2023-03\\2023-03-norfolk-outcomes.csv',
 '.\\2023-03\\2023-03-suffolk-outcomes.csv',
 '.\\2023-04\\2023-04-avon-and-somerset-outcomes.csv',
 '.\\2023-04\\2023-04-cambridgeshire-outcomes.csv',
 '.\\2023-04\\2023-04-cheshire-outcomes.csv',
 '.\\2023-04\\2023-04-cumbria-outcomes.csv',
 '.\\2023-04\\2023-04-derbyshire-outcomes.csv',
 '.\\2023-04\\2023-04-durham-outcomes.csv',
 '.\\2023-04\\2023-04-gloucestershire-outcomes.csv',
 '.\\2023-04\\2023-04-hampshire-outcomes.csv',
 '.\\2023-04\\2023-04-hertfordshire-outcomes.csv',
 '.\\2023-04\\2023-04-lancashire-outcomes.csv',
 '.\\2023-04\\2023-04-norfolk-outcomes.csv',
 '.\\2023-04\\2023-04-suffolk-outcomes.csv',
 '.\\2023-05\\2023-05-avon-and-somerset-outcomes.csv',
 '.\\2023-05\\2023-05-cambridgeshire-outcomes.csv',
 '.\\2023-05\\2023-05-cheshire-outcomes.csv',
 '.\\2023-05\\2023-05-cumbria-outcomes.csv',
 '.\\2023-05\\2023-05-derbyshire-outcomes.csv',
 '.\\2023-05\\2023-05-durham-outcomes.csv',
 '.\\2023-05\\2023-05-gloucestershire-outcomes.csv',
 '.\\2023-05\\2023-05-hampshire-outcomes.csv',
 '.\\2023-05\\2023-05-hertfordshire-outcomes.csv',
 '.\\2023-05\\2023-05-lancashire-outcomes.csv',
 '.\\2023-05\\2023-05-norfolk-outcomes.csv',
 '.\\2023-05\\2023-05-suffolk-outcomes.csv',
 '.\\2023-06\\2023-06-avon-and-somerset-outcomes.csv',
 '.\\2023-06\\2023-06-cambridgeshire-outcomes.csv',
 '.\\2023-06\\2023-06-cheshire-outcomes.csv',
 '.\\2023-06\\2023-06-cumbria-outcomes.csv',
 '.\\2023-06\\2023-06-derbyshire-outcomes.csv',
 '.\\2023-06\\2023-06-durham-outcomes.csv',
 '.\\2023-06\\2023-06-gloucestershire-outcomes.csv',
 '.\\2023-06\\2023-06-hampshire-outcomes.csv',
 '.\\2023-06\\2023-06-hertfordshire-outcomes.csv',
 '.\\2023-06\\2023-06-lancashire-outcomes.csv',
 '.\\2023-06\\2023-06-norfolk-outcomes.csv',
 '.\\2023-06\\2023-06-suffolk-outcomes.csv',
 '.\\2023-07\\2023-07-avon-and-somerset-outcomes.csv',
 '.\\2023-07\\2023-07-cambridgeshire-outcomes.csv',
 '.\\2023-07\\2023-07-cheshire-outcomes.csv',
 '.\\2023-07\\2023-07-cumbria-outcomes.csv',
 '.\\2023-07\\2023-07-derbyshire-outcomes.csv',
 '.\\2023-07\\2023-07-durham-outcomes.csv',
 '.\\2023-07\\2023-07-gloucestershire-outcomes.csv',
 '.\\2023-07\\2023-07-hampshire-outcomes.csv',
 '.\\2023-07\\2023-07-hertfordshire-outcomes.csv',
 '.\\2023-07\\2023-07-lancashire-outcomes.csv',
 '.\\2023-07\\2023-07-norfolk-outcomes.csv',
 '.\\2023-07\\2023-07-suffolk-outcomes.csv',
 '.\\2023-08\\2023-08-avon-and-somerset-outcomes.csv',
 '.\\2023-08\\2023-08-cambridgeshire-outcomes.csv',
 '.\\2023-08\\2023-08-cheshire-outcomes.csv',
 '.\\2023-08\\2023-08-cumbria-outcomes.csv',
 '.\\2023-08\\2023-08-derbyshire-outcomes.csv',
 '.\\2023-08\\2023-08-durham-outcomes.csv',
 '.\\2023-08\\2023-08-gloucestershire-outcomes.csv',
 '.\\2023-08\\2023-08-hampshire-outcomes.csv',
 '.\\2023-08\\2023-08-hertfordshire-outcomes.csv',
 '.\\2023-08\\2023-08-lancashire-outcomes.csv',
 '.\\2023-08\\2023-08-norfolk-outcomes.csv',
 '.\\2023-08\\2023-08-suffolk-outcomes.csv',
 '.\\2023-09\\2023-09-avon-and-somerset-outcomes.csv',
 '.\\2023-09\\2023-09-cambridgeshire-outcomes.csv',
 '.\\2023-09\\2023-09-cheshire-outcomes.csv',
 '.\\2023-09\\2023-09-cumbria-outcomes.csv',
 '.\\2023-09\\2023-09-derbyshire-outcomes.csv',
 '.\\2023-09\\2023-09-durham-outcomes.csv',
 '.\\2023-09\\2023-09-gloucestershire-outcomes.csv',
 '.\\2023-09\\2023-09-hampshire-outcomes.csv',
 '.\\2023-09\\2023-09-hertfordshire-outcomes.csv',
 '.\\2023-09\\2023-09-lancashire-outcomes.csv',
 '.\\2023-09\\2023-09-norfolk-outcomes.csv',
 '.\\2023-09\\2023-09-suffolk-outcomes.csv',
 '.\\2023-10\\2023-10-avon-and-somerset-outcomes.csv',
 '.\\2023-10\\2023-10-cambridgeshire-outcomes.csv',
 '.\\2023-10\\2023-10-cheshire-outcomes.csv',
 '.\\2023-10\\2023-10-cumbria-outcomes.csv',
 '.\\2023-10\\2023-10-derbyshire-outcomes.csv',
 '.\\2023-10\\2023-10-durham-outcomes.csv',
 '.\\2023-10\\2023-10-gloucestershire-outcomes.csv',
 '.\\2023-10\\2023-10-hampshire-outcomes.csv',
 '.\\2023-10\\2023-10-hertfordshire-outcomes.csv',
 '.\\2023-10\\2023-10-lancashire-outcomes.csv',
 '.\\2023-10\\2023-10-norfolk-outcomes.csv',
 '.\\2023-10\\2023-10-suffolk-outcomes.csv',
 '.\\2023-11\\2023-11-avon-and-somerset-outcomes.csv',
 '.\\2023-11\\2023-11-cambridgeshire-outcomes.csv',
 '.\\2023-11\\2023-11-cheshire-outcomes.csv',
 '.\\2023-11\\2023-11-cumbria-outcomes.csv',
 '.\\2023-11\\2023-11-derbyshire-outcomes.csv',
 '.\\2023-11\\2023-11-durham-outcomes.csv',
 '.\\2023-11\\2023-11-gloucestershire-outcomes.csv',
 '.\\2023-11\\2023-11-hampshire-outcomes.csv',
 '.\\2023-11\\2023-11-hertfordshire-outcomes.csv',
 '.\\2023-11\\2023-11-lancashire-outcomes.csv',
 '.\\2023-11\\2023-11-norfolk-outcomes.csv',
 '.\\2023-11\\2023-11-suffolk-outcomes.csv',
 '.\\2023-12\\2023-12-avon-and-somerset-outcomes.csv',
 '.\\2023-12\\2023-12-cambridgeshire-outcomes.csv',
 '.\\2023-12\\2023-12-cheshire-outcomes.csv',
 '.\\2023-12\\2023-12-cumbria-outcomes.csv',
 '.\\2023-12\\2023-12-derbyshire-outcomes.csv',
 '.\\2023-12\\2023-12-durham-outcomes.csv',
 '.\\2023-12\\2023-12-gloucestershire-outcomes.csv',
 '.\\2023-12\\2023-12-hampshire-outcomes.csv',
 '.\\2023-12\\2023-12-hertfordshire-outcomes.csv',
 '.\\2023-12\\2023-12-lancashire-outcomes.csv',
 '.\\2023-12\\2023-12-norfolk-outcomes.csv',
 '.\\2023-12\\2023-12-suffolk-outcomes.csv',
 '.\\2024-01\\2024-01-avon-and-somerset-outcomes.csv',
 '.\\2024-01\\2024-01-cambridgeshire-outcomes.csv',
 '.\\2024-01\\2024-01-cheshire-outcomes.csv',
 '.\\2024-01\\2024-01-cumbria-outcomes.csv',
 '.\\2024-01\\2024-01-derbyshire-outcomes.csv',
 '.\\2024-01\\2024-01-durham-outcomes.csv',
 '.\\2024-01\\2024-01-gloucestershire-outcomes.csv',
 '.\\2024-01\\2024-01-hampshire-outcomes.csv',
 '.\\2024-01\\2024-01-hertfordshire-outcomes.csv',
 '.\\2024-01\\2024-01-lancashire-outcomes.csv',
 '.\\2024-01\\2024-01-norfolk-outcomes.csv',
 '.\\2024-01\\2024-01-suffolk-outcomes.csv',
 '.\\2024-02\\2024-02-avon-and-somerset-outcomes.csv',
 '.\\2024-02\\2024-02-cambridgeshire-outcomes.csv',
 '.\\2024-02\\2024-02-cheshire-outcomes.csv',
 '.\\2024-02\\2024-02-cumbria-outcomes.csv',
 '.\\2024-02\\2024-02-derbyshire-outcomes.csv',
 '.\\2024-02\\2024-02-durham-outcomes.csv',
 '.\\2024-02\\2024-02-gloucestershire-outcomes.csv',
 '.\\2024-02\\2024-02-hampshire-outcomes.csv',
 '.\\2024-02\\2024-02-hertfordshire-outcomes.csv',
 '.\\2024-02\\2024-02-lancashire-outcomes.csv',
 '.\\2024-02\\2024-02-norfolk-outcomes.csv',
 '.\\2024-02\\2024-02-suffolk-outcomes.csv',
 '.\\2024-03\\2024-03-avon-and-somerset-outcomes.csv',
 '.\\2024-03\\2024-03-cambridgeshire-outcomes.csv',
 '.\\2024-03\\2024-03-cheshire-outcomes.csv',
 '.\\2024-03\\2024-03-cumbria-outcomes.csv',
 '.\\2024-03\\2024-03-derbyshire-outcomes.csv',
 '.\\2024-03\\2024-03-durham-outcomes.csv',
 '.\\2024-03\\2024-03-gloucestershire-outcomes.csv',
 '.\\2024-03\\2024-03-hampshire-outcomes.csv',
 '.\\2024-03\\2024-03-hertfordshire-outcomes.csv',
 '.\\2024-03\\2024-03-lancashire-outcomes.csv',
 '.\\2024-03\\2024-03-norfolk-outcomes.csv',
 '.\\2024-03\\2024-03-suffolk-outcomes.csv',
 '.\\2024-04\\2024-04-avon-and-somerset-outcomes.csv',
 '.\\2024-04\\2024-04-cambridgeshire-outcomes.csv',
 '.\\2024-04\\2024-04-cheshire-outcomes.csv',
 '.\\2024-04\\2024-04-cumbria-outcomes.csv',
 '.\\2024-04\\2024-04-derbyshire-outcomes.csv',
 '.\\2024-04\\2024-04-durham-outcomes.csv',
 '.\\2024-04\\2024-04-gloucestershire-outcomes.csv',
 '.\\2024-04\\2024-04-hampshire-outcomes.csv',
 '.\\2024-04\\2024-04-hertfordshire-outcomes.csv',
 '.\\2024-04\\2024-04-lancashire-outcomes.csv',
 '.\\2024-04\\2024-04-norfolk-outcomes.csv',
 '.\\2024-04\\2024-04-suffolk-outcomes.csv',
 '.\\2024-05\\2024-05-avon-and-somerset-outcomes.csv',
 '.\\2024-05\\2024-05-cambridgeshire-outcomes.csv',
 '.\\2024-05\\2024-05-cheshire-outcomes.csv',
 '.\\2024-05\\2024-05-cumbria-outcomes.csv',
 '.\\2024-05\\2024-05-derbyshire-outcomes.csv',
 '.\\2024-05\\2024-05-durham-outcomes.csv',
 '.\\2024-05\\2024-05-gloucestershire-outcomes.csv',
 '.\\2024-05\\2024-05-hampshire-outcomes.csv',
 '.\\2024-05\\2024-05-hertfordshire-outcomes.csv',
 '.\\2024-05\\2024-05-lancashire-outcomes.csv',
 '.\\2024-05\\2024-05-norfolk-outcomes.csv',
 '.\\2024-05\\2024-05-suffolk-outcomes.csv',
 '.\\2024-06\\2024-06-avon-and-somerset-outcomes.csv',
 '.\\2024-06\\2024-06-cambridgeshire-outcomes.csv',
 '.\\2024-06\\2024-06-cheshire-outcomes.csv',
 '.\\2024-06\\2024-06-cumbria-outcomes.csv',
 '.\\2024-06\\2024-06-derbyshire-outcomes.csv',
 '.\\2024-06\\2024-06-durham-outcomes.csv',
 '.\\2024-06\\2024-06-gloucestershire-outcomes.csv',
 '.\\2024-06\\2024-06-hampshire-outcomes.csv',
 '.\\2024-06\\2024-06-hertfordshire-outcomes.csv',
 '.\\2024-06\\2024-06-lancashire-outcomes.csv',
 '.\\2024-06\\2024-06-norfolk-outcomes.csv',
 '.\\2024-06\\2024-06-suffolk-outcomes.csv',
 '.\\2024-07\\2024-07-avon-and-somerset-outcomes.csv',
 '.\\2024-07\\2024-07-cambridgeshire-outcomes.csv',
 '.\\2024-07\\2024-07-cheshire-outcomes.csv',
 '.\\2024-07\\2024-07-cumbria-outcomes.csv',
 '.\\2024-07\\2024-07-derbyshire-outcomes.csv',
 '.\\2024-07\\2024-07-durham-outcomes.csv',
 '.\\2024-07\\2024-07-gloucestershire-outcomes.csv',
 '.\\2024-07\\2024-07-hampshire-outcomes.csv',
 '.\\2024-07\\2024-07-hertfordshire-outcomes.csv',
 '.\\2024-07\\2024-07-lancashire-outcomes.csv',
 '.\\2024-07\\2024-07-norfolk-outcomes.csv',
 '.\\2024-07\\2024-07-suffolk-outcomes.csv',
 '.\\2024-08\\2024-08-avon-and-somerset-outcomes.csv',
 '.\\2024-08\\2024-08-cambridgeshire-outcomes.csv',
 '.\\2024-08\\2024-08-cheshire-outcomes.csv',
 '.\\2024-08\\2024-08-cumbria-outcomes.csv',
 '.\\2024-08\\2024-08-derbyshire-outcomes.csv',
 '.\\2024-08\\2024-08-durham-outcomes.csv',
 '.\\2024-08\\2024-08-gloucestershire-outcomes.csv',
 '.\\2024-08\\2024-08-hampshire-outcomes.csv',
 '.\\2024-08\\2024-08-hertfordshire-outcomes.csv',
 '.\\2024-08\\2024-08-lancashire-outcomes.csv',
 '.\\2024-08\\2024-08-norfolk-outcomes.csv',
 '.\\2024-08\\2024-08-suffolk-outcomes.csv',
 '.\\2024-09\\2024-09-avon-and-somerset-outcomes.csv',
 '.\\2024-09\\2024-09-cambridgeshire-outcomes.csv',
 '.\\2024-09\\2024-09-cheshire-outcomes.csv',
 '.\\2024-09\\2024-09-cumbria-outcomes.csv',
 '.\\2024-09\\2024-09-derbyshire-outcomes.csv',
 '.\\2024-09\\2024-09-durham-outcomes.csv',
 '.\\2024-09\\2024-09-gloucestershire-outcomes.csv',
 '.\\2024-09\\2024-09-hampshire-outcomes.csv',
 '.\\2024-09\\2024-09-hertfordshire-outcomes.csv',
 '.\\2024-09\\2024-09-lancashire-outcomes.csv',
 '.\\2024-09\\2024-09-norfolk-outcomes.csv',
 '.\\2024-09\\2024-09-suffolk-outcomes.csv',
 '.\\2024-10\\2024-10-avon-and-somerset-outcomes.csv',
 '.\\2024-10\\2024-10-cambridgeshire-outcomes.csv',
 '.\\2024-10\\2024-10-cheshire-outcomes.csv',
 '.\\2024-10\\2024-10-cumbria-outcomes.csv',
 '.\\2024-10\\2024-10-derbyshire-outcomes.csv',
 '.\\2024-10\\2024-10-durham-outcomes.csv',
 '.\\2024-10\\2024-10-gloucestershire-outcomes.csv',
 '.\\2024-10\\2024-10-hampshire-outcomes.csv',
 '.\\2024-10\\2024-10-hertfordshire-outcomes.csv',
 '.\\2024-10\\2024-10-lancashire-outcomes.csv',
 '.\\2024-10\\2024-10-norfolk-outcomes.csv',
 '.\\2024-10\\2024-10-suffolk-outcomes.csv',
 '.\\2024-11\\2024-11-avon-and-somerset-outcomes.csv',
 '.\\2024-11\\2024-11-cambridgeshire-outcomes.csv',
 '.\\2024-11\\2024-11-cheshire-outcomes.csv',
 '.\\2024-11\\2024-11-cumbria-outcomes.csv',
 '.\\2024-11\\2024-11-derbyshire-outcomes.csv',
 '.\\2024-11\\2024-11-durham-outcomes.csv',
 '.\\2024-11\\2024-11-gloucestershire-outcomes.csv',
 '.\\2024-11\\2024-11-hampshire-outcomes.csv',
 '.\\2024-11\\2024-11-hertfordshire-outcomes.csv',
 '.\\2024-11\\2024-11-lancashire-outcomes.csv',
 '.\\2024-11\\2024-11-norfolk-outcomes.csv',
 '.\\2024-11\\2024-11-suffolk-outcomes.csv',
 '.\\2024-12\\2024-12-avon-and-somerset-outcomes.csv',
 '.\\2024-12\\2024-12-cambridgeshire-outcomes.csv',
 '.\\2024-12\\2024-12-cheshire-outcomes.csv',
 '.\\2024-12\\2024-12-cumbria-outcomes.csv',
 '.\\2024-12\\2024-12-derbyshire-outcomes.csv',
 '.\\2024-12\\2024-12-durham-outcomes.csv',
 '.\\2024-12\\2024-12-gloucestershire-outcomes.csv',
 '.\\2024-12\\2024-12-hampshire-outcomes.csv',
 '.\\2024-12\\2024-12-hertfordshire-outcomes.csv',
 '.\\2024-12\\2024-12-lancashire-outcomes.csv',
 '.\\2024-12\\2024-12-norfolk-outcomes.csv',
 '.\\2024-12\\2024-12-suffolk-outcomes.csv',
 '.\\2025-01\\2025-01-avon-and-somerset-outcomes.csv',
 '.\\2025-01\\2025-01-cambridgeshire-outcomes.csv',
 '.\\2025-01\\2025-01-cheshire-outcomes.csv',
 '.\\2025-01\\2025-01-cumbria-outcomes.csv',
 '.\\2025-01\\2025-01-derbyshire-outcomes.csv',
 '.\\2025-01\\2025-01-durham-outcomes.csv',
 '.\\2025-01\\2025-01-gloucestershire-outcomes.csv',
 '.\\2025-01\\2025-01-hampshire-outcomes.csv',
 '.\\2025-01\\2025-01-hertfordshire-outcomes.csv',
 '.\\2025-01\\2025-01-lancashire-outcomes.csv',
 '.\\2025-01\\2025-01-norfolk-outcomes.csv',
 '.\\2025-01\\2025-01-suffolk-outcomes.csv',
 '.\\2025-02\\2025-02-avon-and-somerset-outcomes.csv',
 '.\\2025-02\\2025-02-cambridgeshire-outcomes.csv',
 '.\\2025-02\\2025-02-cheshire-outcomes.csv',
 '.\\2025-02\\2025-02-cumbria-outcomes.csv',
 '.\\2025-02\\2025-02-derbyshire-outcomes.csv',
 '.\\2025-02\\2025-02-durham-outcomes.csv',
 '.\\2025-02\\2025-02-gloucestershire-outcomes.csv',
 '.\\2025-02\\2025-02-hampshire-outcomes.csv',
 '.\\2025-02\\2025-02-hertfordshire-outcomes.csv',
 '.\\2025-02\\2025-02-lancashire-outcomes.csv',
 '.\\2025-02\\2025-02-norfolk-outcomes.csv',
 '.\\2025-02\\2025-02-suffolk-outcomes.csv',
 '.\\2025-03\\2025-03-avon-and-somerset-outcomes.csv',
 '.\\2025-03\\2025-03-cambridgeshire-outcomes.csv',
 '.\\2025-03\\2025-03-cheshire-outcomes.csv',
 '.\\2025-03\\2025-03-cumbria-outcomes.csv',
 '.\\2025-03\\2025-03-derbyshire-outcomes.csv',
 '.\\2025-03\\2025-03-durham-outcomes.csv',
 '.\\2025-03\\2025-03-gloucestershire-outcomes.csv',
 '.\\2025-03\\2025-03-hampshire-outcomes.csv',
 '.\\2025-03\\2025-03-hertfordshire-outcomes.csv',
 '.\\2025-03\\2025-03-lancashire-outcomes.csv',
 '.\\2025-03\\2025-03-norfolk-outcomes.csv',
 '.\\2025-03\\2025-03-suffolk-outcomes.csv',
 '.\\2025-04\\2025-04-avon-and-somerset-outcomes.csv',
 '.\\2025-04\\2025-04-cambridgeshire-outcomes.csv',
 '.\\2025-04\\2025-04-cheshire-outcomes.csv',
 '.\\2025-04\\2025-04-cumbria-outcomes.csv',
 '.\\2025-04\\2025-04-derbyshire-outcomes.csv',
 '.\\2025-04\\2025-04-durham-outcomes.csv',
 '.\\2025-04\\2025-04-gloucestershire-outcomes.csv',
 '.\\2025-04\\2025-04-hampshire-outcomes.csv',
 '.\\2025-04\\2025-04-hertfordshire-outcomes.csv',
 '.\\2025-04\\2025-04-lancashire-outcomes.csv',
 '.\\2025-04\\2025-04-norfolk-outcomes.csv',
 '.\\2025-04\\2025-04-suffolk-outcomes.csv',
 '.\\2025-05\\2025-05-avon-and-somerset-outcomes.csv',
 '.\\2025-05\\2025-05-cambridgeshire-outcomes.csv',
 '.\\2025-05\\2025-05-cheshire-outcomes.csv',
 '.\\2025-05\\2025-05-derbyshire-outcomes.csv',
 '.\\2025-05\\2025-05-durham-outcomes.csv',
 '.\\2025-05\\2025-05-gloucestershire-outcomes.csv',
 '.\\2025-05\\2025-05-hampshire-outcomes.csv',
 '.\\2025-05\\2025-05-hertfordshire-outcomes.csv',
 '.\\2025-05\\2025-05-lancashire-outcomes.csv',
 '.\\2025-05\\2025-05-norfolk-outcomes.csv',
 '.\\2025-05\\2025-05-suffolk-outcomes.csv',
 '.\\2025-06\\2025-06-avon-and-somerset-outcomes.csv',
 '.\\2025-06\\2025-06-cambridgeshire-outcomes.csv',
 '.\\2025-06\\2025-06-cheshire-outcomes.csv',
 '.\\2025-06\\2025-06-cumbria-outcomes.csv',
 '.\\2025-06\\2025-06-derbyshire-outcomes.csv',
 '.\\2025-06\\2025-06-durham-outcomes.csv',
 '.\\2025-06\\2025-06-gloucestershire-outcomes.csv',
 '.\\2025-06\\2025-06-hampshire-outcomes.csv',
 '.\\2025-06\\2025-06-hertfordshire-outcomes.csv',
 '.\\2025-06\\2025-06-lancashire-outcomes.csv',
 '.\\2025-06\\2025-06-norfolk-outcomes.csv',
 '.\\2025-06\\2025-06-suffolk-outcomes.csv',
 '.\\2025-07\\2025-07-avon-and-somerset-outcomes.csv',
 '.\\2025-07\\2025-07-cambridgeshire-outcomes.csv',
 '.\\2025-07\\2025-07-cheshire-outcomes.csv',
 '.\\2025-07\\2025-07-cumbria-outcomes.csv',
 '.\\2025-07\\2025-07-derbyshire-outcomes.csv',
 '.\\2025-07\\2025-07-durham-outcomes.csv',
 '.\\2025-07\\2025-07-gloucestershire-outcomes.csv',
 '.\\2025-07\\2025-07-hampshire-outcomes.csv',
 '.\\2025-07\\2025-07-hertfordshire-outcomes.csv',
 '.\\2025-07\\2025-07-lancashire-outcomes.csv',
 '.\\2025-07\\2025-07-norfolk-outcomes.csv',
 '.\\2025-07\\2025-07-suffolk-outcomes.csv',
 '.\\2025-08\\2025-08-avon-and-somerset-outcomes.csv',
 '.\\2025-08\\2025-08-cambridgeshire-outcomes.csv',
 '.\\2025-08\\2025-08-cheshire-outcomes.csv',
 '.\\2025-08\\2025-08-cumbria-outcomes.csv',
 '.\\2025-08\\2025-08-derbyshire-outcomes.csv',
 '.\\2025-08\\2025-08-durham-outcomes.csv',
 '.\\2025-08\\2025-08-gloucestershire-outcomes.csv',
 '.\\2025-08\\2025-08-hampshire-outcomes.csv',
 '.\\2025-08\\2025-08-hertfordshire-outcomes.csv',
 '.\\2025-08\\2025-08-lancashire-outcomes.csv',
 '.\\2025-08\\2025-08-norfolk-outcomes.csv',
 '.\\2025-08\\2025-08-suffolk-outcomes.csv',
 '.\\2025-09\\2025-09-avon-and-somerset-outcomes.csv',
 '.\\2025-09\\2025-09-cambridgeshire-outcomes.csv',
 '.\\2025-09\\2025-09-cheshire-outcomes.csv',
 '.\\2025-09\\2025-09-cumbria-outcomes.csv',
 '.\\2025-09\\2025-09-derbyshire-outcomes.csv',
 '.\\2025-09\\2025-09-durham-outcomes.csv',
 '.\\2025-09\\2025-09-gloucestershire-outcomes.csv',
 '.\\2025-09\\2025-09-hampshire-outcomes.csv',
 '.\\2025-09\\2025-09-hertfordshire-outcomes.csv',
 '.\\2025-09\\2025-09-lancashire-outcomes.csv',
 '.\\2025-09\\2025-09-norfolk-outcomes.csv',
 '.\\2025-09\\2025-09-suffolk-outcomes.csv',
 '.\\2025-10\\2025-10-avon-and-somerset-outcomes.csv',
 '.\\2025-10\\2025-10-cambridgeshire-outcomes.csv',
 '.\\2025-10\\2025-10-cheshire-outcomes.csv',
 '.\\2025-10\\2025-10-cumbria-outcomes.csv',
 '.\\2025-10\\2025-10-derbyshire-outcomes.csv',
 '.\\2025-10\\2025-10-durham-outcomes.csv',
 '.\\2025-10\\2025-10-gloucestershire-outcomes.csv',
 '.\\2025-10\\2025-10-hampshire-outcomes.csv',
 '.\\2025-10\\2025-10-hertfordshire-outcomes.csv',
 '.\\2025-10\\2025-10-lancashire-outcomes.csv',
 '.\\2025-10\\2025-10-norfolk-outcomes.csv',
 '.\\2025-10\\2025-10-suffolk-outcomes.csv',
 '.\\2025-11\\2025-11-avon-and-somerset-outcomes.csv',
 '.\\2025-11\\2025-11-cambridgeshire-outcomes.csv',
 '.\\2025-11\\2025-11-cheshire-outcomes.csv',
 '.\\2025-11\\2025-11-cumbria-outcomes.csv',
 '.\\2025-11\\2025-11-derbyshire-outcomes.csv',
 '.\\2025-11\\2025-11-durham-outcomes.csv',
 '.\\2025-11\\2025-11-gloucestershire-outcomes.csv',
 '.\\2025-11\\2025-11-hampshire-outcomes.csv',
 '.\\2025-11\\2025-11-hertfordshire-outcomes.csv',
 '.\\2025-11\\2025-11-lancashire-outcomes.csv',
 '.\\2025-11\\2025-11-norfolk-outcomes.csv',
 '.\\2025-11\\2025-11-suffolk-outcomes.csv',
 '.\\2025-12\\2025-12-avon-and-somerset-outcomes.csv',
 '.\\2025-12\\2025-12-cambridgeshire-outcomes.csv',
 '.\\2025-12\\2025-12-cheshire-outcomes.csv',
 '.\\2025-12\\2025-12-cumbria-outcomes.csv',
 '.\\2025-12\\2025-12-derbyshire-outcomes.csv',
 '.\\2025-12\\2025-12-durham-outcomes.csv',
 '.\\2025-12\\2025-12-gloucestershire-outcomes.csv',

In [5]:
outcome_df = pd.concat((pd.read_csv(f) for f in outcome_files), ignore_index=True)

In [6]:
outcome_df.info()
outcome_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2920000 entries, 0 to 2919999
Data columns (total 10 columns):
 #   Column        Dtype
---  ------        -----
 0   Crime ID      object
 1   Month         object
 2   Reported by   object
 3   Falls within  object
 4   Longitude     float64
 5   Latitude      float64
 6   Location      object
 7   LSOA code     object
 8   LSOA name     object
 9   Outcome type  object
dtypes: float64(2), object(8)
memory usage: 222.8+ MB

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,e654e620cf71a660f56f13517cadb7862c9fd12c4bf63f...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Unable to prosecute suspect
1,8b96302723123488b3dcf9a7821656a18904869710827c...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Suspect charged
2,8d55cb3717f4229858db526e20caf8bef60d3a91d6a3f2...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Formal action is not in the public interest
3,3d270a8110881aa2f37099f12293b68428d82168b21166...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Unable to prosecute suspect
4,0de2d59f65e7f79c2f75ccf838aea9a576e3171dc7c3cf...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.589352,51.411661,On or near Whitchurch Lane,E01032515,Bristol 053F,Unable to prosecute suspect

In [9]:
street_df.columns = (
    street_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

outcome_df.columns = (
    outcome_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [10]:
outcome_df.columns

Index(['crime_id', 'month', 'reported_by', 'falls_within', 'longitude',
       'latitude', 'location', 'lsoa_code', 'lsoa_name', 'outcome_type'],
      dtype='object')

In [11]:
street_df.columns

Index(['crime_id', 'month', 'reported_by', 'falls_within', 'longitude',
       'latitude', 'location', 'lsoa_code', 'lsoa_name', 'crime_type',
       'last_outcome_category', 'context'],
      dtype='object')

In [12]:
street_df["year"] = street_df["month"].str[:4].astype(int)
street_df["month_num"] = street_df["month"].str[5:7].astype(int)

outcome_df["year"] = outcome_df["month"].str[:4].astype(int)
outcome_df["month_num"] = outcome_df["month"].str[5:7].astype(int)

In [13]:
display(street_df.head(),outcome_df.head())

,crime_id,month,reported_by,falls_within,longitude,latitude,location,lsoa_code,lsoa_name,crime_type,last_outcome_category,context,year,month_num
0,44949804e10105361f806c22620b183ed7b4337bc53c62...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-1.563651,53.550385,On or near Hawthorn Grove,E01007420,Barnsley 016C,Vehicle crime,Status update unavailable,NaN,2023,2
1,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.491146,51.425008,On or near Maximus Gardens,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN,2023,2
2,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.509285,51.409716,On or near Barnard Walk,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN,2023,2
3,df0232499c2a00f19201d41c436bd12608f036f6306a43...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.492876,51.422716,On or near Trajectus Way,E01014399,Bath and North East Somerset 001A,Other theft,Status update unavailable,NaN,2023,2
4,4ccbf045d0c67899cf4cf81ebf83f1d352701604f1a024...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.491146,51.425008,On or near Maximus Gardens,E01014399,Bath and North East Somerset 001A,Public order,Unable to prosecute suspect,NaN,2023,2

,crime_id,month,reported_by,falls_within,longitude,latitude,location,lsoa_code,lsoa_name,outcome_type,year,month_num
0,e654e620cf71a660f56f13517cadb7862c9fd12c4bf63f...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Unable to prosecute suspect,2023,2
1,8b96302723123488b3dcf9a7821656a18904869710827c...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Suspect charged,2023,2
2,8d55cb3717f4229858db526e20caf8bef60d3a91d6a3f2...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Formal action is not in the public interest,2023,2
3,3d270a8110881aa2f37099f12293b68428d82168b21166...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,NaN,NaN,No location,NaN,NaN,Unable to prosecute suspect,2023,2
4,0de2d59f65e7f79c2f75ccf838aea9a576e3171dc7c3cf...,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.589352,51.411661,On or near Whitchurch Lane,E01032515,Bristol 053F,Unable to prosecute suspect,2023,2

In [15]:
street_df["crime_id"].is_unique
street_df["crime_id"].duplicated().sum()

np.int64(610586)

In [16]:
street_df[street_df["crime_id"].duplicated(keep=False)]

,crime_id,month,reported_by,falls_within,longitude,latitude,location,lsoa_code,lsoa_name,crime_type,last_outcome_category,context,year,month_num
1,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.491146,51.425008,On or near Maximus Gardens,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN,2023,2
2,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.509285,51.409716,On or near Barnard Walk,E01014399,Bath and North East Somerset 001A,Anti-social behaviour,NaN,NaN,2023,2
17,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.498613,51.416020,On or near High Street,E01014400,Bath and North East Somerset 001B,Anti-social behaviour,NaN,NaN,2023,2
18,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.499056,51.418356,On or near Pool Barton,E01014400,Bath and North East Somerset 001B,Anti-social behaviour,NaN,NaN,2023,2
19,NaN,2023-02,Avon and Somerset Constabulary,Avon and Somerset Constabulary,-2.510372,51.423406,On or near Durley Lane,E01014400,Bath and North East Somerset 001B,Anti-social behaviour,NaN,NaN,2023,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3651261,NaN,2026-01,Suffolk Constabulary,Suffolk Constabulary,0.426231,52.078834,On or near Leiston Road,E01030114,West Suffolk 020F,Anti-social behaviour,NaN,NaN,2026,1
3651264,NaN,2026-01,Suffolk Constabulary,Suffolk Constabulary,0.427321,52.080898,On or near Horseshoe Lane,E01030115,West Suffolk 021A,Anti-social behaviour,NaN,NaN,2026,1
3651265,NaN,2026-01,Suffolk Constabulary,Suffolk Constabulary,0.426680,52.079841,On or near Greenfields Way,E01030115,West Suffolk 021A,Anti-social behaviour,NaN,NaN,2026,1
3651300,NaN,2026-01,Suffolk Constabulary,Suffolk Constabulary,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN,2026,1
3651301,NaN,2026-01,Suffolk Constabulary,Suffolk Constabulary,NaN,NaN,No Location,NaN,NaN,Anti-social behaviour,NaN,NaN,2026,1

In [17]:
street_df[street_df["crime_id"].duplicated()]["crime_id"].unique()

array([nan,
       '317e4ead081d23d95470964146f4ae97cd395aa295c276ebd4e069b31f7d2100',
       'a92aea4c2b73c6d8cc612033ae7bfb9b03cf2a03e9d8a488820078f53fbcf766',
       ...,
       'a641be0139c84fad76e92a8ea011a29a20829e4e44750c0c0c647bd9c1560d61',
       'e6135f141cd677edacafa4bc713c2013c8695d5079ad918963cfb5669a9affb2',
       '17b084e1eee6c1669678dcb03f072cfc8db2dc4ecaf34ac21cc53d5b0a661c67'],
      shape=(15302,), dtype=object)

In [18]:
street_df["crime_id"].value_counts()[street_df["crime_id"].value_counts() > 1]

crime_id
6198ccbb0df050a7570ef4976ac9c0029993dec216416a6648e1db4b496eb53b    157
a30209f2ff7df17a641b9ef88dcb7e865421b26dfa96f33583353f572e5fa5bd      8
fa1cff6c25fe6c5d016168877f33f55e2db84a9d74f5387e2251fb6d2e2bc6c2      7
08ded05a1fb9b53c1e3e320d41e161ad9c427ea880f63a2a76e2451e25807ece      6
ea659bdd4ed38ac5c9259bb280638a9ab0a1650137f57e2a7efbfe080e285d87      6
                                                                   ...
0a4586022ac4eff9ff6434c381862ccf00d21242b631e8b7270c052137869c16      2
5b2e57c0e3e7abc93d06537778ab8be55b0374015aa82a243f6f861edecd3169      2
f20b4f336b879b213db0d47a76fd908bf6c973fc998257414da52540f2fdff26      2
7108855b22837c0f362338ce380e76c0d984785bd34a2c9603395935c98eb863      2
0832e84343f0021d7842e1e65a8aeacd445fe85dca0e9de670f48e0c6c1f16b4      2
Name: count, Length: 15301, dtype: int64

In [21]:
dupe_counts = (
    street_df["crime_id"]
    .value_counts()
    .sort_values(ascending=False)
)
dupe_counts

crime_id
6198ccbb0df050a7570ef4976ac9c0029993dec216416a6648e1db4b496eb53b    157
a30209f2ff7df17a641b9ef88dcb7e865421b26dfa96f33583353f572e5fa5bd      8
fa1cff6c25fe6c5d016168877f33f55e2db84a9d74f5387e2251fb6d2e2bc6c2      7
08ded05a1fb9b53c1e3e320d41e161ad9c427ea880f63a2a76e2451e25807ece      6
ea659bdd4ed38ac5c9259bb280638a9ab0a1650137f57e2a7efbfe080e285d87      6
                                                                   ...
e56425a27a97dcd3c1b034e46ca68fcce1ea2db477d3a5bd26be47913c84e3d4      1
d458d04cc78d718859c12879d3c53736d62e386489fa3117557ead3bc5b6de0a      1
d9c1cca5a0570a3a6cf9c5c3afd06caa0ec6f75938728938f23ef0108b913f11      1
aabcc5a5420bc9c71b410c4c38d26c88186c43a5f7cda1c3bf5a764f84a7e0aa      1
890774c71e82c68efc90af4e1cf0624cfc99f31d11287640a1a972e611bafbf5      1
Name: count, Length: 3040737, dtype: int64

In [23]:
street_df.isna().sum()

crime_id                  594430
month                          0
reported_by                    0
falls_within                   0
longitude                  87395
latitude                   87395
location                       0
lsoa_code                  87407
lsoa_name                  87407
crime_type                     0
last_outcome_category     594430
context                  3651324
year                           0
month_num                      0
dtype: int64

In [24]:
null_counts = street_df.isna().sum()
null_percent = (street_df.isna().mean() * 100).round(2)

pd.DataFrame({
    "null_count": null_counts,
    "null_percent": null_percent
})

                       null_count  null_percent
crime_id                   594430         16.28
month                           0          0.00
reported_by                     0          0.00
falls_within                    0          0.00
longitude                   87395          2.39
latitude                    87395          2.39
location                        0          0.00
lsoa_code                   87407          2.39
lsoa_name                   87407          2.39
crime_type                      0          0.00
last_outcome_category      594430         16.28
context                   3651324        100.00
year                            0          0.00
month_num                       0          0.00

In [27]:
street_df = street_df[street_df["crime_id"].notna()]
street_df.isna().sum()

crime_id                       0
month                          0
reported_by                    0
falls_within                   0
longitude                  87117
latitude                   87117
location                       0
lsoa_code                  87126
lsoa_name                  87126
crime_type                     0
last_outcome_category          0
context                  3056894
year                           0
month_num                      0
dtype: int64

In [28]:
null_counts = street_df.isna().sum()
null_percent = (street_df.isna().mean() * 100).round(2)

pd.DataFrame({
    "null_count": null_counts,
    "null_percent": null_percent
})

                       null_count  null_percent
crime_id                        0          0.00
month                           0          0.00
reported_by                     0          0.00
falls_within                    0          0.00
longitude                   87117          2.85
latitude                    87117          2.85
location                        0          0.00
lsoa_code                   87126          2.85
lsoa_name                   87126          2.85
crime_type                      0          0.00
last_outcome_category           0          0.00
context                   3056894        100.00
year                            0          0.00
month_num                       0          0.00

In [30]:
outcome_df[outcome_df["crime_id"].duplicated()]["crime_id"].unique()

array(['2751a187292f3d7e7395410f78b5e0e5ad455b98492b2e39fe2664168490ad8e',
       'ffa47a00c8494729e2910513f9f2a2906cc18d75d5d1727de1e98316a38f6fd9',
       'e7cd6d263538c3e4d61f3ad6a8ac9e7b6f941bf184b4f27149be96251a4047b6',
       ...,
       '638c63f7c5e3a9a60f6f4cfaa62e81a2bdcee94f5dedd375bf927b0a9e0d2dfa',
       'ff9007189f08ea6818ad828d7aec347af2a38ad8530fe9c5e4ce82278381d94e',
       '8a2409782df3f5792b44914a29ee45233913643e3f44985ab1aba6ff19eca01b'],
      shape=(247144,), dtype=object)

In [32]:
dupe_counts2 = (
    outcome_df["crime_id"]
    .value_counts()
    .sort_values(ascending=False)
)
dupe_counts2

crime_id
89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a67755c99d4c32f25a0    45
31410185a0d3702c584208a38621f9ea8c77ac62ad3d91f42add3fad542fc99d    44
41ed9838d946e7d20ba35ad3c4887acc3622d7ca486dbae8e724919ac3d7ddf2    44
7d31f911cc3c4836a88061a3173c964c07b3e1e344add8fc76ba59cae482d137    30
6ecafd31e42b0d9cf2250a6945f801fde43963aa4312e3714acb42e631f84f2d    30
                                                                    ..
e8cd9813ea716609af70b37657eff52dda0ce909f4a32b09aa3dbe65b8d5be04     1
15edaa75218e0576a21312a53d76ef40f41f9395fdbdb305577e27e4edebadfe     1
33a3af6bc7da6fa3ab4553d9c586d3e3d1ea2e0f197a085c405577cd1ef05a4b     1
921b47c5604d8f8ca704fa39dea2080286685bd50201fd00199c88edf181d6f2     1
5fed7ba966ead190bab135cdac58b9caefbf73a6de3f757769e872aac27b6ed8     1
Name: count, Length: 2617845, dtype: int64

In [34]:
outcome_df[outcome_df["crime_id"] == "89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a67755c99d4c32f25a0"]

,crime_id,month,reported_by,falls_within,longitude,latitude,location,lsoa_code,lsoa_name,outcome_type,year,month_num
1621642,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621959,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621964,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621971,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621976,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621981,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622062,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622115,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622134,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622139,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622144,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622156,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622161,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622377,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622464,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622472,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622526,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622609,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622687,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622734,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622787,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622969,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1623474,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1786941,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787186,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787353,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787366,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787369,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787374,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787377,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787380,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787519,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787577,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787594,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787597,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787601,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787608,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787612,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787704,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787853,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787908,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787965,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1788027,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1788098,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1788505,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12

In [36]:
rows = outcome_df[outcome_df["crime_id"] == "89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a67755c99d4c32f25a0"]
rows

,crime_id,month,reported_by,falls_within,longitude,latitude,location,lsoa_code,lsoa_name,outcome_type,year,month_num
1621642,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621959,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621964,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621971,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621976,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1621981,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622062,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622115,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622134,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622139,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622144,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622156,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622161,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622377,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622464,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622472,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622526,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622609,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622687,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622734,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622787,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1622969,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1623474,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-10,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,10
1786941,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787186,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787353,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787366,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787369,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787374,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787377,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787380,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787519,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787577,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787594,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787597,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787601,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787608,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787612,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787704,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787853,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787908,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1787965,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1788027,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1788098,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12
1788505,89e5536fa5ed99ffc357ff2828e4d0cd04c531400ced7a...,2024-12,Derbyshire Constabulary,Derbyshire Constabulary,-1.422896,53.234268,On or near Dixon's Road,E01033387,Chesterfield 010F,Suspect charged,2024,12

In [37]:
rows.nunique()

crime_id        1
month           2
reported_by     1
falls_within    1
longitude       1
latitude        1
location        1
lsoa_code       1
lsoa_name       1
outcome_type    1
year            1
month_num       2
dtype: int64

In [38]:
null_counts2 = outcome_df.isna().sum()
null_percent2 = (outcome_df.isna().mean() * 100).round(2)

pd.DataFrame({
    "null_count": null_counts2,
    "null_percent": null_percent2
})

              null_count  null_percent
crime_id               0           0.0
month                  0           0.0
reported_by            0           0.0
falls_within           0           0.0
longitude          64366           2.2
latitude           64366           2.2
location               0           0.0
lsoa_code          64370           2.2
lsoa_name          64370           2.2
outcome_type           0           0.0
year                   0           0.0
month_num              0           0.0

In [39]:
street_df = street_df.drop(columns=["context"])

In [40]:
#remove exact dulicate rows street

before = len(street_df)


street_df = street_df.drop_duplicates()


after = len(street_df)



removed = before - after

before, removed, after

(3056894, 2621, 3054273)

In [41]:
#remove exact dulicate rows outcome

before2 = len(outcome_df)


outcome_df = outcome_df.drop_duplicates()


after2 = len(outcome_df)



removed2 = before2 - after2

before2, removed2, after2

(2920000, 236467, 2683533)

In [46]:
# --- STEP 3: Standardise data types ---

# crime_id should be a string
street_df["crime_id"] = street_df["crime_id"].astype(str)

# year and month_num should be integers
street_df["year"] = street_df["year"].astype(int)
street_df["month_num"] = street_df["month_num"].astype(int)

# longitude and latitude should be floats
street_df["longitude"] = street_df["longitude"].astype(float)
street_df["latitude"] = street_df["latitude"].astype(float)

# month should be a string
street_df["month"] = street_df["month"].astype(str)
street_df.dtypes

crime_id                  object
month                     object
reported_by               object
falls_within              object
longitude                float64
latitude                 float64
location                  object
lsoa_code                 object
lsoa_name                 object
crime_type                object
last_outcome_category     object
year                       int64
month_num                  int64
dtype: object

In [47]:
# --- Validate data types for outcome_df ---

# crime_id should be a string
outcome_df["crime_id"] = outcome_df["crime_id"].astype(str)

# year and month_num should be integers (if they exist)
if "year" in outcome_df.columns:
    outcome_df["year"] = outcome_df["year"].astype(int)

if "month_num" in outcome_df.columns:
    outcome_df["month_num"] = outcome_df["month_num"].astype(int)

# month should be a string (if it exists)
if "month" in outcome_df.columns:
    outcome_df["month"] = outcome_df["month"].astype(str)

# Show the final data types
outcome_df.dtypes

crime_id         object
month            object
reported_by      object
falls_within     object
longitude       float64
latitude        float64
location         object
lsoa_code        object
lsoa_name        object
outcome_type     object
year              int64
month_num         int64
dtype: object

In [48]:
# --- STEP 4: Validate merge keys ---

# crime_ids in street but not in outcomes
street_only = set(street_df["crime_id"]) - set(outcome_df["crime_id"])

# crime_ids in outcomes but not in street
outcome_only = set(outcome_df["crime_id"]) - set(street_df["crime_id"])

# Show counts
len(street_only), len(outcome_only)

(425646, 2754)

In [49]:
# --- STEP 6: Merge street_df and outcome_df ---

merged_df = street_df.merge(
    outcome_df[["crime_id", "outcome_type"]], 
    on="crime_id", 
    how="left"
)

# Check the shape before and after
street_rows = len(street_df)
merged_rows = len(merged_df)

street_rows, merged_rows
#this is wrong befor and after should be identical

(3054273, 3120612)

In [52]:
#
street_clean_df = (
    street_df
    .sort_values(["crime_id", "year", "month_num"])
    .drop_duplicates(subset="crime_id", keep="first")
)

In [53]:
outcome_clean_df = (
    outcome_df
    .sort_values(["crime_id", "year", "month_num"])
    .drop_duplicates(subset="crime_id", keep="last")
)

In [55]:
merged_df = street_clean_df.merge(
    outcome_clean_df[["crime_id", "outcome_type"]],
    on="crime_id",
    how="left"
)
len(street_clean_df), len(merged_df)

## out put sam number same nubmer

(3040737, 3040737)

In [56]:
merged_df["outcome_type"].isna().sum()

np.int64(425646)

In [57]:
merged_df["outcome_type"].notna().sum()

np.int64(2615091)

In [58]:
merged_df["latitude"].isna().sum(), merged_df["longitude"].isna().sum()

(np.int64(85655), np.int64(85655))

In [59]:
merged_df["crime_type"].isna().sum()

np.int64(0)

In [60]:
merged_df[
    (merged_df["latitude"] < 49) |
    (merged_df["latitude"] > 61) |
    (merged_df["longitude"] < -8) |
    (merged_df["longitude"] > 2)
].shape

(0, 14)

In [61]:
merged_df["crime_id"].duplicated().sum()

np.int64(0)

In [62]:
len(merged_df)

3040737

In [63]:
len(street_clean_df)

3040737

In [64]:
street_clean_df.to_csv("street_clean.csv", index=False)
outcome_clean_df.to_csv("outcome_clean.csv", index=False)
merged_df.to_csv("merged_clean.csv", index=False)